# Generated by Django 5.2.5 on 2025-08-22 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover_content_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='cover_image',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='series',
            name='cover_content_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='series',
            name='cover_image',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
