# Generated by Django 5.2.5 on 2025-09-20 13:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_remove_book_genres_series_genres'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='book',
            name='order_in_series',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='book',
            name='publication_year',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='rating',
            name='value',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.RemoveField(
            model_name='rating',
            name='created_at',
        ),
        migrations.CreateModel(
            name='UserSeriesStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('READ', 'Прочитано'), ('PARTIAL', 'Не дочитал'), ('UNREAD', 'Не прочитано')], default='UNREAD', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_statuses', to='books.series')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series_statuses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'series')},
            },
        ),
    ]
